### ISSUE TITLE
variables are not loading even tho GTM  is running on local machine Please check video below

### ISSUE THREAD

**Issue by RashedAlkhatib** [jewuma/mumps-debug#17]
https://drive.google.com/file/d/1bJpfT_aoeKgKphBbCD3VF5dzYjIUhhs0/view?usp=sharing

**Comment by jewuma** [comment]
I've tested with YottaDB all the time, which is mostly compatible with GT.M, but in this case it works a bit different.
the actual problem should be fixed in the new MDEBUG.m version. I still got some strange effects from GT.M for which I didn't find a reason. Maybe one of the community knows what happens, when i get a GTM-I-NOZBRK error.

**Comment by RashedAlkhatib** [comment]
@jewuma thanks for the fast response "Great effort keep up",
when do you think the new MDEBUG.m will be released  ?

**Comment by jewuma** [comment]
The version is online. Please take it from the files here
