### ISSUE TITLE
Testing with YottaDB / GTm in docker container

### ISSUE THREAD

**Issue by rafael5** [jewuma/mumps-debug#4]
Thank you for this plugin!

Would it be possible to provide some test code so we can see this in action on GT.m / YottaDB?

Instructions to install this within a docker container?  (i.e. the YottaDB docker container)

Again ,thank you for this excellent plugin.

rafael

**Comment by jensstraffr** [comment]
I don't know if I got your question right, but I'll try to give a helpful answer.

Well I've not so much experience with docker.

In the google-mumps group I've posted a way to install yottadb from scratch on a linux machine.

see https://groups.google.com/forum/?fromgroups#!topic/comp.lang.mumps/BxhZCgn5jSI

In short there's the Instruction for a yottadb-Installation.

Following commands were performed (as root to save several sudos):

apt install libicu-dev    (needed for UTF-8 support)

mkdir /tmp/tmp ; wget -P /tmp/tmp https://gitlab.com/YottaDB/DB/YDB/raw/master/sr_unix/ydbinstall.sh
cd /tmp/tmp ; chmod +x ydbinstall.sh
./ydbinstall.sh --utf8 default --verbose r1.28
mkdir /var/lib/yottadb
mkdir /var/lib/yottadb/r
mkdir /var/lib/yottadb/g
mkdir /var/lib/yottadb/o
chmod 775 -R /var/lib/yottadb
groupadd yottadb
chgrp yottadb -R /var/lib/yottadb/
usermod -aG yottadb <username>

then you copy the MDEBUG.m File into the /var/lib/yottadb/r directory.
In this directory you can also put your own M-Programs to debug.

In my case I'm using VS Code on a win10 Machine and the above directory is served by a samba server so that I can map it to a windows path like x:\

Maybe this helps a bit.
